ASP.NET/Books/src/Books/Models/Book.cs
using System;

namespace Books.Models
{
    public class Book
    {
        public Guid Id { get; set; }

        public string Title { get; set; }

        public DateTime PublishedIn { get; set; }

        //public bool Owns { get; set; }

        //public bool Read { get; set; }

        public Book()
        {
            Id = Guid.NewGuid();
        }
    }
}

ASP.NET/Books/src/Books/Controllers/AuthorsController.cs
using Books.Models;
using Microsoft.AspNet.Mvc;

namespace Books.Controllers
{
    public class AuthorsController : BaseController
    {

        [HttpGet("authors")] // display the list of all authors
        public IActionResult Index()
        {
            return View("index", Data.GetAuthors());
        }

        [HttpGet("authors/add")] // display the details page for a new author
        public IActionResult Add()
        {
            ViewData["Title"] = "New author";
            return View("details");
        }

        [HttpPost("authors/add")] // add the new new author and redirect to "authors"
        public IActionResult Add(Author a)
        {
            Data.AddAuthor(a);
            return DefaultView();
        }

        [HttpGet("authors/{id}/edit")] // display the details page for an existing author
        public IActionResult Edit(string id)
        {
            ViewData["Title"] = "Edit author";
            return PerformForAuthor(id, a => { return View("details", a); });
        }

        [HttpPost("authors/{id}/edit")] // edit the author and redirect to "authors"
        public IActionResult Edit(Author a)
        {
            Data.EditAuthor(a);
            return DefaultView();
        }

        [HttpGet("authors/{id}/delete")] // display the "really delete?" page
        public IActionResult Delete(string id)
        {
            return PerformForAuthor(id, a => { return View("delete", a); });
        }

        [HttpPost("authors/{id}/delete")] // delete the author
        public IActionResult Delete(Author a)
        {
            Data.DeleteAuthor(a);
            return Redirect("/authors");
        }

    }
}

ASP.NET/Books/src/Books/Controllers/BooksController.cs
using Books.Models;
using Microsoft.AspNet.Mvc;

namespace Books.Controllers
{
    public class BooksController : BaseController
    {

        [HttpGet("authors/{authorId}/books")] // display the books page for an author
        public IActionResult Index(string authorId)
        {
            return PerformForAuthor(authorId, a => { return View("index", a); });
        }

        [HttpGet("authors/{authorId}/books/add")] // display the details page for a new book
        public IActionResult Add(string authorId)
        {
            return PerformForAuthor(authorId, 
                a => 
                {
                    ViewData["Title"] = "New book for " + a.Name;
                    return View("details");
                });
        }

        [HttpPost("authors/{authorId}/books/add")] // add the new new book and redirect to "books"
        public IActionResult Add(string authorId, Book b)
        {
            return PerformForAuthor(authorId,
                a =>
                {
                    Data.AddBook(a, b);
                    return RedirectToAction("index", new { authorId = authorId });
                });
        }

        [HttpGet("authors/{authorId}/books/{id}/edit")] // display the details page for an existing book
        public IActionResult Edit(string authorId, string id)
        {
            ViewData["Title"] = "Edit book";
            return PerformForBook(id, b => { return View("details", b); });
        }

        [HttpPost("authors/{authorId}/books/{id}/edit")] // edit the book and redirect to "books"
        public IActionResult Edit(string authorId, Book b)
        {
            Data.EditBook(b);
            return RedirectToAction("index", new { authorId = authorId });
        }

        [HttpGet("authors/{authorId}/books/{id}/delete")] // display the "really delete?" page
        public IActionResult Delete(string authorId, string id)
        {
            return PerformForBook(id, b => { return View("delete", b); });
        }

        [HttpPost("authors/{authorId}/books/{id}/delete")] // delete the book
        public IActionResult Delete(string authorId, Book b)
        {
            Data.DeleteBook(b);
            return RedirectToAction("index", new { authorId = authorId });
        }

    }
}

ASP.NET/Books/src/Books/Views/Books/Delete.cshtml
@model Book
@using Books.Helpers

<h2>Delete book</h2>

<p>Really delete @Model.Title ?</p>

<form asp-controller="Books" asp-action="Delete" method="post">
    <button class="btn btn-xs btn-default" type="submit">OK</button>
    @Html.ActionLinkClass("Cancel", "index", null, "btn btn-xs btn-default")
</form>

ASP.NET/Books/src/Books/Views/Books/Details.cshtml
@model Book
@using Books.Helpers

<h2>@ViewData["Title"]</h2>

<form asp-controller="Authors" asp-action="Create" method="post">
    <div class="form-group">
        <label for="Title">Title:</label>
        <input asp-for="Title" class="form-control" type="text" id="Name" placeholder="Enter title here" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <button class="btn btn-xs btn-default" type="submit">OK</button>
    @Html.ActionLinkClass("Cancel", "", null, "btn btn-xs btn-default")
</form>

ASP.NET/Books/src/Books/Views/Books/Index.cshtml
@model Author
@using Books.Helpers

<h2>Books for @Model.Name</h2>

<div class="container">
    @foreach (Book b in Model.Books)
    {
        <div class="row">
            <p class="col-lg-10 col-md-10 col-sm-10 col-xs-10">@b.Title</p>
            @Html.ActionLinkClass("Edit", "edit", new { id = b.Id }, "col-xs-1 btn btn-xs btn-success")
            @Html.ActionLinkClass("Delete", "delete", new { id = b.Id }, "col-xs-1 btn btn-xs btn-danger")
        </div>
    }
</div>

<p>
    @Html.ActionLinkClass("Create New", "Add", new { authorId = Model.Id }, "btn btn-xs btn-success")
</p>